apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: curl-container
  restartPolicy: Always
