apiVersion: v1
kind: Pod
metadata:
  labels:
    name: secrets-test
  name: secrets-test
spec:
  nodeName: server-01a
  volumes:
    - name: "secretstest"
      secret:
        secretName: my-secret
  containers:
    - image: nginx
      name: awebserver
      volumeMounts:
        - mountPath: "/tmp/mysec"
          name: "secretstest"
